config/routes.rb
Rails.application.routes.draw do
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'messages/index'
  get 'conversations/index'
  get 'static_pages/concept_page'
  get'static_pages/team_page'
  get '/libsearch' => 'static_pages#libsearch', :as => 'libsearch_page'

  get '/search' => 'static_pages#search', :as => 'search_page'

  devise_for :users
  root "static_pages#index", page: "home"
  resources :users
  
  resources :library_items
  resources :wishlist_items, only: [:create, :destroy]


  resources :mangas, except: [:destroy] do
    resources :library_items
    resources :wishlist_items, only: [:create, :destroy]
  end
  #========================
  # Routes Private messages
  #========================
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  # Contact route path
  resources :contacts, only: [:index, :new, :create]
  resources :categories, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :join_manga_categories
    has_many :mangas, through: :join_manga_categories
  
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/contact.rb
class Contact < MailForm::Base

	attribute :name,      :validate => true
	attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message

	
	def headers
		{
			:subject => "Contact Form Inquiry",
			:to => "kasu@yopmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	belongs_to :sender, class_name: "User", foreign_key: "sender_id"
	belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
	belongs_to :library_item
	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :receiver_id

	#==============================================================================
	#	method between which will allow us to find the conversation "between" to users, 
	# 	regardless of who is the sender and who is the receiver.
	# 	To create a class method with ActiveRecord, we use the scope method, like so:
	#===============================================================================
	scope :between, -> (sender_id,receiver_id) do
    where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
	end

	#===============================================================================
	# leaving our views and controllers as clean as possible. 
	# We can remove the receiver variable from the conversations index page and move 
	# the logic into the model:
	#================================================================================
	def recipient(current_user)
    	self.sender_id == current_user.id ? self.receiver : self.sender
  	end
	
	#=========================================================
	# display the number of unread messages in a conversation
	#=========================================================
	def unread_message_count(current_user)
    	self.messages.where("user_id != ? AND read = ?", current_user.id, false).count
  	end
end

app/models/join_manga_category.rb
class JoinMangaCategory < ApplicationRecord
    belongs_to :category
    belongs_to :manga
end

app/models/library_item.rb
class LibraryItem < ApplicationRecord
  belongs_to :user
  belongs_to :manga
  has_many :conversations, dependent: :destroy
  
#   def self.search(search)  
#     where("lower(manga.title) LIKE :search OR lower(library_items.manga.title) LIKE :search", search: "%#{search.downcase}%").uniq   
#  end

end

app/models/manga.rb
class Manga < ApplicationRecord
  has_many :library_items
  has_many :users, through: :library_items
  has_many :wishlist_items
  has_many :join_manga_categories
  has_many :categories, through: :join_manga_categories

  has_one_attached :cover

  #cette methode prend un nombre en parametre (7), et renvoie une array de tout les nombres ([1, 2, 3, 4, 5, 6, 7])
  def integer_to_array(volumes)
    all_volumes = []
    (1..volumes).each do |volume|
      all_volumes << volume
    end
    return all_volumes
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  
  #==================================
  #  display the time of the message
  #  in a more human readable way:
  #==================================
    def message_time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end

    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  has_many :library_items
  has_many :mangas, through: :library_items
  has_many :wishlist_items
  
  after_create :welcome_send
  
    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end
  
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
    belongs_to :user
    belongs_to :manga
end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  def index
    @pagy, @mangas = pagy(Manga.all) 
    @categories = Category.all

    if params[:category_id]
      @category = Category.includes(:mangas).find(params[:category_id])                     
      @products = @category.mangas
    else
      @manga = Manga.all
    end   
    @all_libraries = []
    LibraryItem.all.each{|item| @all_libraries << item.manga.id}
  end

  def show
    @manga = Manga.find(params[:id])
    @items = LibraryItem.where(manga:@manga)
    @all_volumes = @manga.integer_to_array(@manga.volume)
    @item = LibraryItem.new

  end
  
  def edit
    @manga = Manga.find(params[:id])
  end

  def new
    @manga = Manga.new
  end

  def create
    manga = Manga.create(manga_params)
    redirect_to manga_path(manga.id)
  end
  

  def update
  end

  def destroy
  end

  def manga_params
      params.require(:manga).permit(:image_url, :title, :author, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :is_user?
  before_action :set_conversation, only: [:show]
    
 

  def show
    @user = User.find(params[:id])
    @user_collection = LibraryItem.where(user: current_user)
    @user_wishlist = WishlistItem.where(user: current_user)
  end

  def edit
    @user_collection = LibraryItem.where(user: current_user)
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(name: params[:user][:name])
      redirect_to '/'
    end
  end
  

  private
  
  def is_user?
    @user = User.find(params[:id])
    unless current_user == @user
      flash[:alert] = "action impossible !"
      redirect_to "/"
    end
  end

  def set_conversation
    @conversation = Conversation.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/mangas/_mangaCard.html copy.erb
<div class='container'>
	<div class="container-fluid mt-2">
		<div class="row m-2 card-all">
			<% @mangas.each do |manga|%>
					
		<article class="card-last-manga card--1">
			<div class="card__img" style="background-image: url('<%= manga.image_url %>')"></div>
			<a href="#" class="card_link">
			<div class="card__img--hover" style="background-image: url('<%= manga.image_url %>')"></div>
			</a>
			<div class="card__info">
			<h3 class="card__title"><% if @all_libraries.include?(manga.id) %><%= image_tag 'available.png', class:"available mb-1"%><% end %> <%= manga.title.capitalize %></h3>
				<% manga.categories.each do |category| %>
				<span><small><%= link_to category.name, category_path(category.id) %></small></span>
				<%end%><br/>
			<span class="card__by">by <%= manga.author%></span><br>
			<%= link_to "Voir le manga", manga_path(manga), class: 'btn btn-info mt-2'%>
			</div>
		</article>
					
			<% end %>
		</div>
		<%= pagy_bootstrap_nav(@pagy).html_safe%>
	</div>
</div>

app/views/mangas/_mangaCard2.html copy.erb
			<div class="container d-flex justify-content-around">
				<div class="row justify-content-between">
					<div class="col-9 card-all">
						<% @mangas.each do |manga|%>
							<article class="card-last-manga card--1">
								<div class="card__img" style="background-image: url('<%= manga.image_url %>')"></div>
									<a href="#" class="card_link">
								<div class="card__img--hover" style="background-image: url('<%= manga.image_url %>')"></div>
								</a>
								<div class="card__info">
									<%= link_to manga.title.capitalize, library_item_path(manga), class: "card__title"%>
									<h5><span>par <%=manga.author%></span></h5>
									<% manga.categories.each do |category| %>
									<%= link_to category.name, category_path(category.id) %>
									<%end%>
								<%= link_to "Voir le manga", manga_path(manga), class: 'btn btn-info mt-2'%>
								</div>
							</article>	
						<% end %>
					</div>
					<div class="col-2 justify-content-around">
						<%= link_to 'all', root_path  %> <br>
						<% @categories.each do |category| %>                 
						<%= link_to category.name, category_path(category) %> <br>  
						<% end %>
					</div>
				</div>
			</div>
				<%= pagy_bootstrap_nav(@pagy).html_safe%>

app/views/mangas/_mangaCard2.html.erb
			<div class="container d-flex justify-content-around">
				<div class="row justify-content-between">
						<% @mangas.each do |manga|%>
							<article class="card-last-manga card--1">
								<div class="card__img" style="background-image: url('<%= manga.image_url %>')"></div>
									<a href="#" class="card_link">
								<div class="card__img--hover" style="background-image: url('<%= manga.image_url %>')"></div>
								</a>
								<div class="card__info">
									<h3 class="card__title"><% if @all_libraries.include?(manga.id) %><%= image_tag 'available.png', class:"available mb-1"%><% end %> <%= manga.title.capitalize %></h3>
									<h5><span>par <%=manga.author%></span></h5>
									<% manga.categories.each do |category| %>
									<%= link_to category.name, category_path(category.id) %>
									<%end%>
								<%= link_to "Voir le manga", manga_path(manga), class: 'btn btn-info mt-2'%>
								</div>
							</article>	
						<% end %>
				</div>
			</div>
				<%= pagy_bootstrap_nav(@pagy).html_safe%>

app/views/mangas/create.html.erb
<h1>Mangas#create</h1>
<p>Find me in app/views/mangas/create.html.erb</p>

app/views/mangas/destroy.html.erb
<h1>Mangas#destroy</h1>
<p>Find me in app/views/mangas/destroy.html.erb</p>

app/views/mangas/edit.html.erb
<%= simple_form_for @manga do |f| %>
  <%= f.input :title %>
  <%= f.input :cover, as: :file %>
  <%= f.input :author %>
  <%= f.input :description %>
  <%= f.button :submit %>
  <%= f.button :submit %>
<% end %>

app/views/mangas/index.html.erb
<h2 class='text-center pt-5'> Partage tes Mangas</h2>
<h4 class='text-center'> Trouve les mangas que tu souhaites partager et constitue ta bibliothèque pour les autres utilisateurs </h4>
<%= render "shared/searchbar" %>

<%= render 'mangaCard2'%>

app/views/mangas/new.html.erb
<%= simple_form_for @manga do |f| %>
  <%= f.input :title %>
  <%= f.file_field :cover %>
  <%= f.input :author %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/mangas/show.html.erb
<div class="container-fluid">
  <div class="container-fluid p-5 background-manga text-white">
    <div class="mr-5">
      <% if @manga.cover.attached? %>
        <%= image_tag @manga.cover %>	
      <% else %>			
        <img class='img-manga-show' src="<%= @manga.image_url %>" alt="Manga-item">
      <% end  %>
    </div>
    <div class="description-manga ml-5">
      <h2><%= @manga.title.capitalize %></h2>
      <h3>  Auteur : <%= @manga.author %> </h3>
      <h3> Description </h3>
      <p><%= @manga.description %></p>
     <!-- <%= link_to "Ajouter à ma Bibliothèque", manga_library_items_path(@manga.id), method: "POST", class:"btn btn-secondary" %> -->
      <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal">
        Je propose
      </button>
      <!-- Modal Library -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header text-dark">
              <h5 class="modal-title" id="exampleModalLabel"><%= @manga.title %></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body text-dark">
             <%= simple_form_for [@manga, @item], :url => manga_library_items_path(@manga.id), :method => :post do |f| %>
                <%= f.input :volume, :collection => @all_volumes, :selected => [1..@manga.volume] %>
                <%= f.input :state_description, :label => "Etat du manga", input_html: { autocomplete: 'off' }, class: "description-form" %>
        
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Annuler</button>
              <%= f.button :submit, 'Ajouter', class: 'btn btn-secondary' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <!-- Modal END -->

   
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal2">
        J'ajoute à ma Wishlist
      </button>
      <!-- Modal Wishlist -->
      <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header text-dark">
              <h5 class="modal-title" id="exampleModalLabel"><strong><%= @manga.title %></strong></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
              <% if @all_volumes.length != 0 %>
                <div class="modal-body text-dark">
                
                <%= simple_form_for @manga, :url => manga_wishlist_items_path(@manga.id), :method => :post do |f| %>
                    <%=  f.input :volume, :collection => @all_volumes, :selected => [1..@manga.volume] %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Annuler</button>
                  <%= f.button :submit, 'Ajouter', class: 'btn btn-secondary' %>
                  <% end %>
              <% else %>

                   <div class="modal-body text-dark">
                    <h5>Ce manga ne contient qu'un seul tome, ajouter le à votre wishlist en cliquant sur le bouton ajouter</h5>
                <%= simple_form_for @manga, :url => manga_wishlist_items_path(@manga.id), :method => :post do |f| %>
                   
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Annuler</button>
                  <%= f.button :submit, 'Ajouter', class: 'btn btn-secondary' %>
                  <% end %>


              <% end %>
               <!-- Modal END -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container py-5">
    <h2 class="text-center"> Les membres qui proposent ce Manga </h2>
    <div class="all-show-manga px-5">
      <% @items.each do |item|%>
        <article class="card-last-manga card-show-manga card--1">
          <div class="card__img" style="background-image: url('<%= item.manga.image_url %>')"></div>
          <a href="<%=library_item_path(item.id)%>" class="card_link">
            <div class="card__img--hover" style="background-image: url('<%= item.manga.image_url %>')"></div>
          </a>
          <div class="card__info">
            <h3 class="card__title">Tome n° : <%= item.volume %></h3>
            <h4>Membre : <%= item.user.name %></h4>
            <%= link_to "Demander ce Manga", library_item_path(item.id), class:"btn btn-outline-secondary my-2" %>
          </div>
        </article>
      <%end%>
    </div>
  </div>
</div>

app/views/mangas/update.html.erb
<h1>Mangas#update</h1>
<p>Find me in app/views/mangas/update.html.erb</p>