config/routes.rb
Rails.application.routes.draw do
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'messages/index'
  get 'conversations/index'
  get 'static_pages/concept_page'
  get'static_pages/team_page'
  get '/libsearch' => 'static_pages#libsearch', :as => 'libsearch_page'

  get '/search' => 'static_pages#search', :as => 'search_page'

  devise_for :users
  root "static_pages#index", page: "home"
  resources :users
  
  resources :library_items
  resources :wishlist_items, only: [:create, :destroy]


  resources :mangas, except: [:destroy] do
    resources :library_items
    resources :wishlist_items, only: [:create, :destroy]
  end
  #========================
  # Routes Private messages
  #========================
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  # Contact route path
  resources :contacts, only: [:index, :new, :create]
  resources :categories, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :join_manga_categories
    has_many :mangas, through: :join_manga_categories
  
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/contact.rb
class Contact < MailForm::Base

	attribute :name,      :validate => true
	attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message

	
	def headers
		{
			:subject => "Contact Form Inquiry",
			:to => "kasu@yopmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	belongs_to :sender, class_name: "User", foreign_key: "sender_id"
	belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
	belongs_to :library_item
	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :receiver_id

	#==============================================================================
	#	method between which will allow us to find the conversation "between" to users, 
	# 	regardless of who is the sender and who is the receiver.
	# 	To create a class method with ActiveRecord, we use the scope method, like so:
	#===============================================================================
	scope :between, -> (sender_id,receiver_id) do
    where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
	end

	#===============================================================================
	# leaving our views and controllers as clean as possible. 
	# We can remove the receiver variable from the conversations index page and move 
	# the logic into the model:
	#================================================================================
	def recipient(current_user)
    	self.sender_id == current_user.id ? self.receiver : self.sender
  	end
	
	#=========================================================
	# display the number of unread messages in a conversation
	#=========================================================
	def unread_message_count(current_user)
    	self.messages.where("user_id != ? AND read = ?", current_user.id, false).count
  	end
end

app/models/join_manga_category.rb
class JoinMangaCategory < ApplicationRecord
    belongs_to :category
    belongs_to :manga
end

app/models/library_item.rb
class LibraryItem < ApplicationRecord
  belongs_to :user
  belongs_to :manga
  has_many :conversations, dependent: :destroy
  
#   def self.search(search)  
#     where("lower(manga.title) LIKE :search OR lower(library_items.manga.title) LIKE :search", search: "%#{search.downcase}%").uniq   
#  end

end

app/models/manga.rb
class Manga < ApplicationRecord
  has_many :library_items
  has_many :users, through: :library_items
  has_many :wishlist_items
  has_many :join_manga_categories
  has_many :categories, through: :join_manga_categories

  has_one_attached :cover

  #cette methode prend un nombre en parametre (7), et renvoie une array de tout les nombres ([1, 2, 3, 4, 5, 6, 7])
  def integer_to_array(volumes)
    all_volumes = []
    (1..volumes).each do |volume|
      all_volumes << volume
    end
    return all_volumes
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  
  #==================================
  #  display the time of the message
  #  in a more human readable way:
  #==================================
    def message_time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end

    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  has_many :library_items
  has_many :mangas, through: :library_items
  has_many :wishlist_items
  
  after_create :welcome_send
  
    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end
  
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
    belongs_to :user
    belongs_to :manga
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @manga = LibraryItem.last(4)
    @user = User.last(3)
  end

  def search  
    if params[:search].blank?  
      redirect_to(mangas_path, alert: "Champ vide!") and return  
    else  
      @parameter = params[:search].downcase  
      @results = Manga.all.where("lower(title) LIKE :search", search: "%#{@parameter}%")
    end   
  end  

  def libsearch  

    if params[:search].blank? 
      redirect_to(library_items_path, alert: "Champ vide!") and return 
    else  
      @libparameter = params[:search].downcase   
      @items = []
      
      LibraryItem.all.each do |item|
        if (item.manga.title).include?(params[:search])
        @items << item
          end
        end       
    end 
  end
  
  # @libresults = LibraryItem.all.where("lower(self.manga.title) LIKE :search", search: "%#{@libparameter}%")  
  # puts @libresults
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :is_user?
  before_action :set_conversation, only: [:show]
    
 

  def show
    @user = User.find(params[:id])
    @user_collection = LibraryItem.where(user: current_user)
    @user_wishlist = WishlistItem.where(user: current_user)
  end

  def edit
    @user_collection = LibraryItem.where(user: current_user)
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(name: params[:user][:name])
      redirect_to '/'
    end
  end
  

  private
  
  def is_user?
    @user = User.find(params[:id])
    unless current_user == @user
      flash[:alert] = "action impossible !"
      redirect_to "/"
    end
  end

  def set_conversation
    @conversation = Conversation.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/_card-user.html.erb
	<div class="m-2 card-user-all">
    
		<% @user.each do |user|%>
    
				
					<div class="card-user">
            <%if user.avatar.attached?%>
              <%= image_tag user.avatar, class: "img-user" %>
            <% else %>
              <%= image_tag "kirua.jpg", class: "img-user" %>
            <%end%>
            <p class="card-time"><%= time_ago_in_words(user.created_at) %></p>
						<h4 class="card-title"><%= user.name %></h4>
					</div>
				
		<% end %>
	</div>

app/views/static_pages/_card.html.erb
<div class="container-fluid mt-2">
	<div class="row m-2 card-all">
		<% @manga.each do |manga|%>
				
      <article class="card-last-manga card--1">
        <div class="card__img" style="background-image: url('<%= manga.manga.image_url %>')"></div>
        <a href="<%=library_item_path(manga)%>" class="card_link">
          <div class="card__img--hover" style="background-image: url('<%= manga.manga.image_url %>')"></div>
        </a>
        <div class="card__info">
           <%= link_to manga.manga.title.capitalize, library_item_path(manga), class: "card__title"%>
          <h5><span>par <%=manga.manga.author%></span></h5>
          <% manga.manga.categories.each do |category| %>
          <%= link_to category.name, category_path(category.id) %>
          <%end%>
        </div>
      </article>
				
		<% end %>
	</div>
</div>

app/views/static_pages/concept_page.html.erb
<div class="container-fluid" id="fond"><br>
  <h1 class="text-center"> Découvrez Kasu</h1>
    <h1 class="text-center">Echangez vos Mangas contre des Kasu Points !</h1>
      <div class="text-center">
        <h3 class="text-center">Bienvenue dans la communauté de passionnés de manga.</h3>
        <h3>Grâce à Kasu vous pourrez dévorer tout les mangas que vous voulez à moindre coût et échanger votre passion avec notre communauté</h3>
        <h3>Le bon plan pour lire moins cher toute l'année !</h3>
        <h3>Facile et économique.</h3>
      </div><br>
        <h2 class="text-center mb-4">Comment ça fonctionne ?</h2> 
      <div class="container">
        <div class="row">
          <div class="text-center col-sm">
            <%= image_tag 'achete.png', class:"icon-explication icon1 mb-4"%>
            <h3> Partage /Échange</h3>
            <p>Rentres ton manga dans la  bibliothèque du site une personne est intéressée par ton manga qui se trouve dans sa whishlist (ou liste de souhait).Il prend contact avec toi via la messagerie du site. Vous convenez soit d'un envoi, soit d'un échange direct dans ta ville ou région.</p>
          </div>
          <div class="text-center col-sm">
            <%= image_tag 'recois.png', class:"icon-explication icon1 mb-4"%>
            <h3>Reçois</h3>
            <p>Quand tu échanges un livre, tu reçois un Kasu point qui te permettra à ton tour d’acquérir un nouveau manga ensuite si tu le désires, soit tu gardes ce manga, soit tu le rentres dans la bibliothèque.</p>
          </div>
          <div class="text-center col-sm">
            <%= image_tag 'echange.png', class:"icon-explication icon1 mb-4"%>
            <h3>Choisis</h3>
            <p>J'indique les livres que je possède en entrant simplement les mangas dans la bibliothèque ou en cliquant sur le bouton "ajouter un manga". Lorsqu'un membre souhaite un de mes livres, je lui expédie et je gagne 1 kasu Point par livre. Avec celui-ci je commande les livres que je désire.</p>
          </div>
        </div>
        <h2 class="mb-5">Inscrivez-vous gratuitement, les 100 premiers inscrits recevront 1 Kasu Point</h2>
  </div>
</div>

app/views/static_pages/index.html.erb
<header>
  <div class="container-fluid" id="fond">
    <%= image_tag 'rectangle1.png', class:"rectangle1 animate__animated animate__fadeInDownBig"%>
    <%= image_tag 'rouge1.png', class:"rouge1 animate__animated animate__fadeInUpBig"%>
    <%= image_tag 'rectangle2.png', class:"rectangle2 animate__animated animate__fadeInDownBig"%>
    <%= image_tag 'rectangle3.png', class:"rectangle3 animate__animated animate__fadeInUpBig"%>
    <%= image_tag 'rectangle4.png', class:"rectangle4 animate__animated animate__fadeInDownBig"%>
    <%= image_tag 'rectangle5.png', class:"rectangle5 animate__animated animate__fadeInUpBig"%>
    <%= image_tag 'rouge2.png', class:"rouge2 animate__animated animate__fadeInDownBig"%>
    <%= image_tag 'rectangle6.png', class:"rectangle6 animate__animated animate__fadeInUpBig"%>
    <div class="container-title animate__animated animate__fadeInLeftBig">
      <h1 class="title">La marketplace des mangas !</h1>
      <a class="btn btn-secondary" href="<%=library_items_path%>">Découvrez-les</a>
    </div>
  </div>
</header>

 <%= render "shared/searchbar" %>

<main>
  <div class="container-fluid section1">
    <h2 class="text-center">Rejoins la communauté Kasu et échange tes Mangas en toute simplicité</h2>
    <div class="container d-flex justify-content-around all-icon">
      <div class="text-center mr-5">
        <a class="" href="<%= mangas_path %>"><%= image_tag 'echange.png', class:"icon-explication icon1 mb-4"%></a>
        <h3>1.Je crée ma bibliothèque</h3>
        <p>Met en ligne les mangas <br /> que tu ne veux plus.</p>
      </div>
      <div class="text-center mr-5">
        <a class="" href="<%=static_pages_concept_page_path%>"><%= image_tag 'recois.png', class:"icon-explication icon1 mb-4"%></a>
        <h3>Reçois</h3>
        <p>Reçois des kasu points<br />une fois ton vieux manga échangé.</p>
      </div>
      <div class="text-center">
        <a class="" href="<%= library_items_path %>"><%= image_tag 'achete.png', class:"icon-explication icon1 mb-4"%></a>
        <h3>Choisis</h3>
        <p>Achète les mangas que tu veux<br />grâce à tes kasu points !</p>
      </div>
    </div>
  </div>

  <div class="section2">
    <h2 class="text-center">Les derniers mangas ajoutés</h2>
    <div class="container d-flex justify-content-around">
      <%= render "card" %>
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to "Les mangas disponibles", library_items_path, class: 'btn btn-outline-dark'%>

    </div>
  </div>

  <div class="section3">
    <h2 class="text-center">Les nouveaux membres</h2>
    <%= render "card-user" %>
  </div>

  <div class="section4">
    <%= image_tag "sig_up.png", class:"img-sign" %>
    <h4>Toi aussi rejoins la communauté et échange en toute simplicité !</h4>
    <a href="<%=new_user_registration_path%>" class="btn btn-danger">s'inscrire</a>
  </div>

</main>

app/views/static_pages/libsearch.html.erb
  <div class="container m-3 d-flex align-items-start">
    <h3>Résultat de ta recherche</h3>  
    <div class="result m-5">
      <% @items.each do |result| %>  
        <ul>
          <% if result.user != current_user %>
            <li><b> <%= result.manga.title.capitalize %> </b> de <b> <%= result.manga.author %> </b>-<b> TOME N°<%= result.volume %> </b> proposé par	<%= result.user.name %> <%= link_to "Voir le manga", library_item_path(result)%> </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <div class="section5">
    <%= image_tag "sig_up.png", class:"img-sign" %>
    <h3>Ton Manga n'y est pas ? Ajoute-le à ta whishlist  </h5>
    <a href="<%=mangas_path%>" class="btn btn-danger">Construire ma wishlist </a>
  </div>

app/views/static_pages/search.html.erb
  
  <div class="container m-3 d-flex align-items-start">
    <h3>Résultat de ta recherche</h3>  
    <div class="result m-5">
          <% @results.each do |result| %>  
          <ul>
            <li><b> <%= result.title.capitalize %> </b> de <b> <%= result.author %> </b> 	<%= link_to "Voir le manga", manga_path(result)%> </li>
          </ul>
      <% end %>
    </div>
  </div>

        <div class="section5">
    <%= image_tag "sig_up.png", class:"img-sign" %>
    <h3><b>Toi aussi rejoins la communauté et échange en toute simplicité !</b></h3>
    <a href="<%=new_user_registration_path%>" class="btn btn-danger">s'inscrire</a>
  </div>

app/views/static_pages/team_page.html.erb
<div class="container-fluid" id="fond"><br>
  <h1 class="text-center bl">Notre équipe de Developpeur</h1>
  <div class="container">
    <div class="row">
      <article class="card-last-manga card--1 col-sm">
        <div class="text-center col">
          <div class="card__img" style="background-image: url('https://i.pinimg.com/originals/e0/9e/7a/e09e7a95a3f9baacc28c1cf48400f9ea.jpg')"></div>
            <div class="card__img--hover" style="background-image: url('https://i.pinimg.com/originals/e0/9e/7a/e09e7a95a3f9baacc28c1cf48400f9ea.jpg')"></div>
            <div class="card__info">
            <h3 class="card__title">Dylan</h3>
          </div>
        </div>
      </article>

      <article class="card-last-manga card--1 col-sm">
        <div class="text-center col">
          <div class="card__img" style="background-image: url('https://image.winudf.com/v2/image/Y29tLmdhbmFzZGV2Lmhpc29rYS53YWxscGFwZXJfc2NyZWVuXzJfMTUxNzAwNjI5OF8wMjA/screen-2.jpg?fakeurl=1&type=.jpg')"></div>
            <div class="card__img--hover" style="background-image: url('https://image.winudf.com/v2/image/Y29tLmdhbmFzZGV2Lmhpc29rYS53YWxscGFwZXJfc2NyZWVuXzJfMTUxNzAwNjI5OF8wMjA/screen-2.jpg?fakeurl=1&type=.jpg')"></div>
            <div class="card__info">
                <h3 class="card__title">Youcef</h3>
            </div>
        </div>
      </article>

      <article class="card-last-manga card--1 col-sm">
        <div class="text-center col">
          <div class="card__img" style="background-image: url('https://images-na.ssl-images-amazon.com/images/I/716DAbx1UAL._AC_SL1185_.jpg')"></div>
            <div class="card__img--hover" style="background-image: url('https://images-na.ssl-images-amazon.com/images/I/716DAbx1UAL._AC_SL1185_.jpg')"></div>
            <div class="card__info">
              <h3 class="card__title">Stephen</h3>
            </div>
        </div>
      </article>

      <article class="card-last-manga card--1 col-sm">
        <div class="text-center col">
          <div class="card__img" style="background-image: url('https://besthqwallpapers.com/Uploads/30-9-2020/142350/thumb2-piccolo-4k-green-neon-lights-dragon-ball-warrior.jpg')"></div>
            <div class="card__img--hover" style="background-image: url('https://besthqwallpapers.com/Uploads/30-9-2020/142350/thumb2-piccolo-4k-green-neon-lights-dragon-ball-warrior.jpg')"></div>
            <div class="card__info">
              <h3 class="card__title">Jules</h3>
            </div>
        </div>
      </article>

      <article class="card-last-manga card--1 col-sm">
        <div class="text-center col">
          <div class="card__img" style="background-image: url('https://www.coque-unique.com/clothes/powerbank-large-kakashi-sharingan-white.jpg')"></div>
            <div class="card__img--hover" style="background-image: url('https://www.coque-unique.com/clothes/powerbank-large-kakashi-sharingan-white.jpg')"></div>
            <div class="card__info">
              <h3 class="card__title">Gaëtan</h3>
            </div>
        </div>
      </article>
    </div>
  </div>
</div>