config/routes.rb
Rails.application.routes.draw do
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'messages/index'
  get 'conversations/index'
  get 'static_pages/concept_page'
  get'static_pages/team_page'
  get '/libsearch' => 'static_pages#libsearch', :as => 'libsearch_page'

  get '/search' => 'static_pages#search', :as => 'search_page'

  devise_for :users
  root "static_pages#index", page: "home"
  resources :users
  
  resources :library_items
  resources :wishlist_items, only: [:create, :destroy]


  resources :mangas, except: [:destroy] do
    resources :library_items
    resources :wishlist_items, only: [:create, :destroy]
  end
  #========================
  # Routes Private messages
  #========================
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  # Contact route path
  resources :contacts, only: [:index, :new, :create]
  resources :categories, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :join_manga_categories
    has_many :mangas, through: :join_manga_categories
  
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/contact.rb
class Contact < MailForm::Base

	attribute :name,      :validate => true
	attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message

	
	def headers
		{
			:subject => "Contact Form Inquiry",
			:to => "kasu@yopmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	belongs_to :sender, class_name: "User", foreign_key: "sender_id"
	belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
	belongs_to :library_item
	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :receiver_id

	#==============================================================================
	#	method between which will allow us to find the conversation "between" to users, 
	# 	regardless of who is the sender and who is the receiver.
	# 	To create a class method with ActiveRecord, we use the scope method, like so:
	#===============================================================================
	scope :between, -> (sender_id,receiver_id) do
    where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
	end

	#===============================================================================
	# leaving our views and controllers as clean as possible. 
	# We can remove the receiver variable from the conversations index page and move 
	# the logic into the model:
	#================================================================================
	def recipient(current_user)
    	self.sender_id == current_user.id ? self.receiver : self.sender
  	end
	
	#=========================================================
	# display the number of unread messages in a conversation
	#=========================================================
	def unread_message_count(current_user)
    	self.messages.where("user_id != ? AND read = ?", current_user.id, false).count
  	end
end

app/models/join_manga_category.rb
class JoinMangaCategory < ApplicationRecord
    belongs_to :category
    belongs_to :manga
end

app/models/library_item.rb
class LibraryItem < ApplicationRecord
  belongs_to :user
  belongs_to :manga
  has_many :conversations, dependent: :destroy
  
#   def self.search(search)  
#     where("lower(manga.title) LIKE :search OR lower(library_items.manga.title) LIKE :search", search: "%#{search.downcase}%").uniq   
#  end

end

app/models/manga.rb
class Manga < ApplicationRecord
  has_many :library_items
  has_many :users, through: :library_items
  has_many :wishlist_items
  has_many :join_manga_categories
  has_many :categories, through: :join_manga_categories

  has_one_attached :cover

  #cette methode prend un nombre en parametre (7), et renvoie une array de tout les nombres ([1, 2, 3, 4, 5, 6, 7])
  def integer_to_array(volumes)
    all_volumes = []
    (1..volumes).each do |volume|
      all_volumes << volume
    end
    return all_volumes
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  
  #==================================
  #  display the time of the message
  #  in a more human readable way:
  #==================================
    def message_time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end

    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  has_many :library_items
  has_many :mangas, through: :library_items
  has_many :wishlist_items
  
  after_create :welcome_send
  
    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end
  
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
    belongs_to :user
    belongs_to :manga
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :is_user?
  before_action :set_conversation, only: [:show]
    
 

  def show
    @user = User.find(params[:id])
    @user_collection = LibraryItem.where(user: current_user)
    @user_wishlist = WishlistItem.where(user: current_user)
  end

  def edit
    @user_collection = LibraryItem.where(user: current_user)
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(name: params[:user][:name])
      redirect_to '/'
    end
  end
  

  private
  
  def is_user?
    @user = User.find(params[:id])
    unless current_user == @user
      flash[:alert] = "action impossible !"
      redirect_to "/"
    end
  end

  def set_conversation
    @conversation = Conversation.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/library_items_helper.rb
module LibraryItemsHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="mt-5 pt-5">

<div class="container">


        <%= image_tag 'profile_banner.png', class:"rectangle1 animate__animated animate__fadeInDownBig"%>

    <div class="row">
        <h4 class="mt-1">Changer de pseudo</h4>
        <%= simple_form_for @user do |f| %>
            <div class="form-inputs">
                <%= f.input :name, label: false %>
            </div>
            <%= f.button :submit, "changer",class: "btn-primary" %>
        <% end %>
    </div>


<ul>
<% @user_collection.each do |item| %>
    <li> <%= item.manga.title.capitalize %> <%= item.manga.author %> <%= item.id %>  <%= link_to "Supprimer de ma bibliothèque", library_item_path(item.id), method: "delete",  :data => {:confirm => 'Êtes-vous sûr de vouloir supprimer ce manga?'} %>
        <br/><%= link_to "Consulter la page de votre manga", library_item_path(item.id) %>
    </li>

<% end %>

<%= link_to "Ajouter un manga à votre collection", mangas_path, class: 'btn btn-primary' %>
</ul>




</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Se connecter", new_session_path(resource_name), class:"links-form" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "S'inscrire", new_registration_path(resource_name), class:"links-form" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Mot de passe oublié ?", new_password_path(resource_name), class:"links-form" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class:"links-form" %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class:"links-form" %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="container-fluid">
<div class="col d-flex flex-column justify-content-end profile-banner ">
<div class="row d-flex justify-content-center align-items-center pb-4 mb-5">
    <div class="big-circle position-absolute">
    </div>

    <div class="small-circle position-absolute">
        <%if @user.avatar.attached?%>
            <%= image_tag @user.avatar, class: "small-circle" %>
        <% else %>
            <%= image_tag "kirua.jpg", class: "small-circle"%>
        <%end%>
    </div>
</div>
<div class="row d-flex justify-content-center">
    <h2><strong><%= @user.name.capitalize %></strong></h2>
</div>
<div class="row d-flex justify-content-center">
    <h2><strong><%= @user.token_state %> Kasu Point<% if  @user.token_state > 1  %>s<% end %></strong></h2>
</div>
<div class="row d-flex justify-content-center  pb-3">
    <h5><strong><%= @user.email %></strong></h5>
</div>
<div class="row d-flex justify-content-center pb-5 mb-2">
    <%= link_to "Editer mon profil", edit_user_registration_path(@user.id), class: "btn btn-primary" %>
	<% if @conversation != nil %>
	<a href='<%= conversation_messages_path(@conversation) %>' class= 'mx-4 btn btn-info'>Mes messages
		<% if !@conversation.unread_message_count(current_user).zero? %>
			(<%= @conversation.unread_message_count(current_user) %>)
		<% end %>
	</a>
	<% end %>
</div>
</div>




<div class="row pt-5 mt-5 d-flex justify-content-around">
<div class="col">
    <div class="row d-flex justify-content-center mb-2">
        <h4><strong>Ma collection</strong></h4>
    </div>
    <div class="row d-flex justify-content-center">
     <% if @user_collection.length == 0%>
          <h5>Votre bibliothèque est vide.</h5>
    <% else %>
    <ul class="w-75">
        <% @user_collection.each do |item| %>
            <li class="d-flex justify-content-between li-collection pl-4 pr-4 rounded library-<%= item.id %>"> 
                    <p class="mb-0"> <strong><%= item.manga.title.capitalize %></strong><% if item.volume %>(<%= item.volume %>)<% end %> de <em><%= item.manga.author %></em></p>
             <%= link_to library_item_path(item.id), method: "delete",  :data => {:confirm => 'Êtes-vous sûr de vouloir supprimer ce manga?'}, remote: true do %>
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash red trash-icon" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg>
            <% end %>
            </li> 
        <% end %>
        <% end %>
    </ul>
    </div>
     <div class="row d-flex justify-content-center">
        <%= link_to "Ajouter un manga", mangas_path, class: 'btn btn-secondary mb-5' %>
    </div>
</div>

<div class="col">
    <div class="row d-flex justify-content-center">
         <h4><strong>Ma wishlist</strong></h4>
    </div>
    <div class="row d-flex justify-content-center">
        <% if @user_wishlist.length == 0 %>
            <h5>Votre wishlist est vide.</h5>
        <% else %>
         <ul class="w-75">
        <% @user_wishlist.each do |item| %>
            <li class="d-flex justify-content-between li-collection pl-4 pr-4 rounded wish-<%= item.id %>" > 
                 <p class="mb-0"> <strong><%= item.manga.title.capitalize %></strong><% if item.volume %>(<%= item.volume %>)<% end %> de <em><%= item.manga.author %></em></p>
             <%= link_to wishlist_item_path(item.id), method: "delete", :data => {:confirm => 'Êtes-vous sûr de vouloir supprimer ce manga?'},  remote: true do %>
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash red trash-icon" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg>
            <% end %>
            </li> 
          
        <% end %>
        <% end  %>
    </ul>
    </div>
    <div class="row d-flex justify-content-center">
        <%= link_to "Ajouter un manga", mangas_path, class: 'btn btn-secondary mb-5' %>
    </div>
</div>
</div>
</div>