config/routes.rb
Rails.application.routes.draw do
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'messages/index'
  get 'conversations/index'
  get 'static_pages/concept_page'
  get'static_pages/team_page'
  get '/libsearch' => 'static_pages#libsearch', :as => 'libsearch_page'

  get '/search' => 'static_pages#search', :as => 'search_page'

  devise_for :users
  root "static_pages#index", page: "home"
  resources :users
  
  resources :library_items
  resources :wishlist_items, only: [:create, :destroy]


  resources :mangas, except: [:destroy] do
    resources :library_items
    resources :wishlist_items, only: [:create, :destroy]
  end
  #========================
  # Routes Private messages
  #========================
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  # Contact route path
  resources :contacts, only: [:index, :new, :create]
  resources :categories, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :join_manga_categories
    has_many :mangas, through: :join_manga_categories
  
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/contact.rb
class Contact < MailForm::Base

	attribute :name,      :validate => true
	attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message

	
	def headers
		{
			:subject => "Contact Form Inquiry",
			:to => "kasu@yopmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	belongs_to :sender, class_name: "User", foreign_key: "sender_id"
	belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
	belongs_to :library_item
	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :receiver_id

	#==============================================================================
	#	method between which will allow us to find the conversation "between" to users, 
	# 	regardless of who is the sender and who is the receiver.
	# 	To create a class method with ActiveRecord, we use the scope method, like so:
	#===============================================================================
	scope :between, -> (sender_id,receiver_id) do
    where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
	end

	#===============================================================================
	# leaving our views and controllers as clean as possible. 
	# We can remove the receiver variable from the conversations index page and move 
	# the logic into the model:
	#================================================================================
	def recipient(current_user)
    	self.sender_id == current_user.id ? self.receiver : self.sender
  	end
	
	#=========================================================
	# display the number of unread messages in a conversation
	#=========================================================
	def unread_message_count(current_user)
    	self.messages.where("user_id != ? AND read = ?", current_user.id, false).count
  	end
end

app/models/join_manga_category.rb
class JoinMangaCategory < ApplicationRecord
    belongs_to :category
    belongs_to :manga
end

app/models/library_item.rb
class LibraryItem < ApplicationRecord
  belongs_to :user
  belongs_to :manga
  has_many :conversations, dependent: :destroy
  
#   def self.search(search)  
#     where("lower(manga.title) LIKE :search OR lower(library_items.manga.title) LIKE :search", search: "%#{search.downcase}%").uniq   
#  end

end

app/models/manga.rb
class Manga < ApplicationRecord
  has_many :library_items
  has_many :users, through: :library_items
  has_many :wishlist_items
  has_many :join_manga_categories
  has_many :categories, through: :join_manga_categories

  has_one_attached :cover

  #cette methode prend un nombre en parametre (7), et renvoie une array de tout les nombres ([1, 2, 3, 4, 5, 6, 7])
  def integer_to_array(volumes)
    all_volumes = []
    (1..volumes).each do |volume|
      all_volumes << volume
    end
    return all_volumes
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  
  #==================================
  #  display the time of the message
  #  in a more human readable way:
  #==================================
    def message_time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end

    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  has_many :library_items
  has_many :mangas, through: :library_items
  has_many :wishlist_items
  
  after_create :welcome_send
  
    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end
  
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
    belongs_to :user
    belongs_to :manga
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KasuProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
    <%= favicon_link_tag asset_path('logo3.png') %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    
    <%= render "shared/navbar" %>
    <% flash.each do |name, msg|%>
      <div class='text-center alert-position alert alert-<%= name %>'>
        <%= msg %>
      </div>
    <%end%>


    <%= yield %>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="page-footer font-small mdb-color lighten-3 pt-4">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">

  <!-- Grid row -->
  <div class="row">

    <!-- Grid column -->
    <div class="col-md-4 col-lg-3 mr-auto my-md-4 my-0 mt-4 mb-1">

    <!-- Content -->
    <h5 class="font-weight-bold text-uppercase mb-4">Notre site :</h5>
    <p>Grâce à Kasu vous pourrez dévorer tout les mangas que vous voulez à moindre coût et échanger votre passion avec notre communauté ! </p>

    </div>
    <!-- Grid column -->

    <hr class="clearfix w-100 d-md-none">

    <!-- Grid column -->
    <div class="col-md-2 col-lg-2 mx-auto my-md-4 my-0 mt-4 mb-1">

    <!-- Links -->
    <h5 class="font-weight-bold text-uppercase mb-4">A propos</h5>

    <ul class="list-unstyled">
      <li>
      <p>
        <a href="<%=static_pages_concept_page_path%>">NOTRE CONCEPT</a>
      </p>
      </li>
      <li>
      <p>
        <a href="<%=static_pages_team_page_path%>">NOTRE EQUIPE</a>
      </p>
      </li>
      <li>
      <p>
        <a href="<%= new_contact_path%>">NOUS CONTACTER</a>
      </p>
      </li>
    </ul>

    </div>
    <!-- Grid column -->

    <hr class="clearfix w-100 d-md-none">

    <!-- Grid column -->
    <div class="col-md-4 col-lg-3 mx-auto my-md-4 my-0 mt-4 mb-1">

    <!-- Contact details -->
    <h5 class="font-weight-bold text-uppercase mb-4">Contact</h5>

    <ul class="list-unstyled">
      <li>
      <p>
          <i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
      </li>
      <li>
      <p>
          <i class="fas fa-envelope mr-3"></i> info@example.com</p>
      </li>
      <li>
      <p>
          <i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
      </li>
    </ul>

    </div>
    <!-- Grid column -->

    <hr class="clearfix w-100 d-md-none">

    <!-- Grid column -->
    <div class="col-md-2 col-lg-2 text-center mx-auto my-4">

    <!-- Social buttons -->
    <h5 class="font-weight-bold text-uppercase mb-4">Follow Us</h5>

    <ul class="list-unstyled">
      <li>
      <p>
        <a type="button" class="btn-floating btn-fb">
          <i class="fab fa-facebook-f"></i>
        </a>
      </li>
      <li>
      <p>
        <a type="button" class="btn-floating btn-tw">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
      <li>
      <p>
        <a type="button" class="btn-floating btn-gplus">
          <i class="fab fa-google-plus-g"></i>
        </a>
      </li>
        
    </ul>
    
    </div>


  </div>

  <div class="footer-copyright text-center py-3">© 2020 Copyright :
  <a href="#">Girondins de Paris</a>
  </div>

</footer>

app/views/shared/_libsearchbar.html.erb
    <div class="container d-flex justify-content-center pt-2" >
      <ul class="search_bar mt-5" >
          <%= form_tag(libsearch_page_path, :method => "get",   
          class: 'navbar-form navbar-left') do %>  
            <div class="input-group my-2">  
              <%= search_field_tag :search, params[:search], placeholder: "Tape le nom du manga que tu cherches", class: "form-control" %>  
              <div class="input-group-btn mx-3">  
                <%= button_tag "Trouver un Manga", :class => 'btn btn-danger glyphicon glyphicon-search',:name => nil%>  
              </div>  
            </div>  
          <% end %>
      </ul>
    </div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light py-3 sticky-top" id="navbar">
  <a href='<%= root_path%>' class="brand-link"><%= image_tag 'logo3.png', class:"brand text-prim", size: "60x60" %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarColor03">
  
    <ul class="navbar-nav navbar-center">
      <li class="nav-item active">
          <%= link_to "Accueil", root_path, class: 'nav-link' %>
      </li>

      <li class="nav-item active">
          <%= link_to "Proposer", mangas_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
          <%= link_to "Trouver", library_items_path, class: 'nav-link' %>
      </li>
    
    </ul>

      <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
      <% if user_signed_in?%>
        <% if current_user.name == "Guest" %>
          <li class="pt-2 mr-1"> <%= current_user.name %>
            <%= link_to "changer", edit_user_registration_path(current_user) %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Profil/Quitter</a>
          <div class="dropdown-menu menu-nav" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item menu-nav" <%= link_to "Sign out", destroy_user_session_path, method: :delete %></a>
            <a class="dropdown-item menu-nav" <%= link_to "Profil", user_path(current_user) %></a>
          </div>
        </li>
        <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Se Connecter/S'inscrire</a>
          <div class="dropdown-menu menu-nav" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item menu-nav" href="<%=new_user_session_path%>">Se connecter</a>
            <a class="dropdown-item menu-nav" href="<%=new_user_registration_path%>">S'inscrire</a>
          </div>
      </ul> 
      <% end %>
    </div>
  </nav>

app/views/shared/_searchbar.html.erb
    <div class="container d-flex justify-content-center pt-2" >
      <ul class="search_bar mt-5" >
          <%= form_tag(search_page_path, :method => "get",   
          class: 'navbar-form navbar-left') do %>  
            <div class="input-group my-2">  
              <%= search_field_tag :search, params[:search], placeholder: "Tape le manga que tu souhaites échanger", class: "form-control" %>  
              <div class="input-group-btn mx-3">  
                <%= button_tag "J'échange mon Manga", :class => 'btn btn-danger glyphicon glyphicon-search',:name => nil%>  
              </div>  
            </div>  
          <% end %>
      </ul>
    </div>